Test con algoritmos de WorkshopLLMs,Transformers y GPT en NLP

In [7]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import pipeline
import torch

Analisis de sentimiento

In [8]:
tokenizer = AutoTokenizer.from_pretrained("finiteautomata/beto-sentiment-analysis")
model = AutoModelForSequenceClassification.from_pretrained("finiteautomata/beto-sentiment-analysis")
pipe_beto = pipeline("sentiment-analysis",model=model,tokenizer=tokenizer)

In [9]:
texto = "lo peor que he viste, pero puede mejorar"

In [10]:
pipe_beto(texto)

[{'label': 'NEU', 'score': 0.8687551617622375}]

***

Reconocimiento de entidades nombradas (NER)

In [11]:
model_roberta = "MMG/xlm-roberta-large-ner-spanish"
tokenizer = AutoTokenizer.from_pretrained(model_roberta)
model = AutoModelForSequenceClassification.from_pretrained(model_roberta)
pipe_ner = pipeline("ner",aggregation_strategy="simple",model=model,tokenizer=tokenizer)

c:\Users\Guille\anaconda3\envs\Sentiment\lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Guille\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

KeyboardInterrupt: 

In [27]:
texto = "El presidente Pedro Sánchez, junto con su equipo de gobierno, se reunió con la canciller alemana Angela Merkel en Berlín para discutir temas de cooperación bilateral, incluyendo acuerdos comerciales y políticas de migración. Durante la reunión, ambos líderes intercambiaron puntos de vista sobre la situación internacional y destacaron la importancia de fortalecer los lazos entre sus países."
results = pipe_ner(texto)
results

IndexError: invalid index to scalar variable.

***

Test de Nicholas Renotte https://www.youtube.com/watch?v=szczpgOEdXs

Instanciado de modelo

In [28]:
tokenizer = AutoTokenizer.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

model = AutoModelForSequenceClassification.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

In [33]:
tokens = tokenizer.encode('lo peor que e visto en mi vida', return_tensors='pt')
tokens

tensor([[  101, 10387, 89664, 10126,   147, 21963, 10109, 11793, 11966,   102]])

In [34]:
result = model(tokens)
result

SequenceClassifierOutput(loss=None, logits=tensor([[ 2.5394,  0.5508, -1.0102, -2.0812,  0.0399]],
       grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [35]:
result.logits

tensor([[ 2.5394,  0.5508, -1.0102, -2.0812,  0.0399]],
       grad_fn=<AddmmBackward0>)

In [36]:
# devuelve el indice con el mayor valor
torch.argmax(result.logits)

tensor(0)

In [55]:
tokenizer = AutoTokenizer.from_pretrained('microsoft/deberta-large-mnli')

model = AutoModelForSequenceClassification.from_pretrained('microsoft/deberta-large-mnli')

Some weights of the model checkpoint at microsoft/deberta-large-mnli were not used when initializing DebertaForSequenceClassification: ['config']
- This IS expected if you are initializing DebertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DebertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [50]:
tokens = tokenizer.encode('lo peor que e visto en toda mi vida, jamas voy a volver', return_tensors='pt')
tokens

tensor([[    1,  4082,  3723,   368,  1192,   364,   748,   661,   139,  1177,
             7,  6106, 11163,   748,  4347,     6, 11914,   281, 32098,    10,
         13103,  2802,     2]])

In [51]:
result = model(tokens)
result

SequenceClassifierOutput(loss=None, logits=tensor([[ 0.3077,  1.6331, -1.7742]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [52]:
result.logits

tensor([[ 0.3077,  1.6331, -1.7742]], grad_fn=<AddmmBackward0>)

In [54]:
torch.argmax(result.logits)

tensor(1)

In [9]:
rest_google_reviews.isna().sum()

Unnamed: 0        0
user_id           0
name_x            0
text          57322
dtype: int64

***

Test con las api de GPT 3.5

In [98]:
import openai

In [101]:
openai.api_key = "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"

In [104]:
def get_response(indicacion:str,texto:str):
    prompt = indicacion + "\'\'\'" + texto + "\'\'\'"
    response = openai.Completion.create(model="gpt-3.5-turbo",
                                        prompt=prompt,
                                        max_token=50,
                                        temperature=0.2)
    return response["choices"][0]["text"].strip()

In [105]:
indicacion = "Clasifica el siguiente texto segun su sentimiento en: un numero del 1 al 1o"
texto = "la ideologia de genero es una mentira"

respuesta = get_response(indicacion,texto)

RateLimitError: You exceeded your current quota, please check your plan and billing details.